pip install requests
pip install pyside6
pip install pyaudio
pip install numpy
pip install azure-cognitiveservices-speech
pip install pycountry
pip install spotipy
pip install mpv
pip install google-api-python-client